function data = ch08_run_processing_chain(params)
    % 运行第八章默认处理链：回波矩阵 -> 距离压缩 -> 多普勒处理
    [tx, mf, k] = ch08_make_lfm_pulse(params.B, params.Tp, params.fs);
    rx_matrix = ch08_simulate_echo_matrix(params, k);
    [range_data, range_axis] = ch08_range_compress(rx_matrix, mf, params.c, params.fs);

    rd_map = fftshift(fft(range_data, [], 1), 1);
    rd_power = abs(rd_map);
    peak_value = max(rd_power(:));
    if peak_value > 0
        rd_power = rd_power / peak_value;
    end

    doppler_freq = (-params.Npulse/2:params.Npulse/2-1) * params.PRF / params.Npulse;
    vel_axis = doppler_freq * params.lambda / 2;

    data = struct(...
        'tx', tx, ...
        'mf', mf, ...
        'k', k, ...
        'rx_matrix', rx_matrix, ...
        'range_data', range_data, ...
        'range_axis', range_axis, ...
        'rd_map', rd_map, ...
        'rd_power', rd_power, ...
        'vel_axis', vel_axis);
end
